require "user.options"
require "user.keymaps"
require "user.winbar"
require "user.plugins"
require "user.cmp"
require("user.material").config()
require "user.lsp"
require "user.lsp.null-ls"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
